### ISSUE TITLE
Jinja objects as filter parameters

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/vertx-search#15]
Jinja filter parameters are strings, so if we mention an object in filter parameters, its toString value goes to the filter.  Not ideal, particularly when it's a long list of synonyms, stopwords, or similar.

**Comment by ke4roh** [comment]
Implement com.hubspot.jinjava.lib.filter.AdvancedFilter

**Comment by LightGuard** [comment]
Do we need to do this for all of our filters?

**Comment by ke4roh** [comment]
No, only for filters that take list or map parameters.
